#!/usr/bin/env python3
"""Lightness-banded re-run of the k=5 / k=6 search, plus the opaque-ground
hatch rule for the banded k=5 palettes.  Writes BAND_RESULTS.md.

    python3 band.py            # full
    python3 band.py --quick    # coarse grid only
    SEED=1 python3 band.py     # different restarts; best-known is merged

Same machinery as measure.py (palette_search.py), with one constraint added:
every series must sit inside a lightness band, so the winning set reads as one
family rather than pairing a near-black with a near-white.
"""

import json
import os

from palette_search import (COARSE, FINE, KICKS, OKABE_HUE, OKABE_ITO,
                            RESTARTS, SEED_SALT, THEMES, VISIONS,
                            MAX_CHROMA_NEUTRAL, MIN_CONTRAST, HUE_TOL,
                            best_palette, candidates_for_hue, ciede2000,
                            composite_over, contrast_ratio, labs4, lch,
                            meets_contrast, neutral_candidates, pair_min,
                            score, set_report, itertools, time)

BANDS = {'light': (30.0, 72.0), 'dark': (45.0, 88.0)}
C_FLOOR = 25.0
CACHE_PATH = 'band_best_known.json'
UNBANDED_PATH = 'best_known.json'

t0 = time.time()
L = []
W = L.append


def fnum(x, nd=1):
    return f'{x:.{nd}f}'


def load(p):
    return json.load(open(p)) if os.path.exists(p) else {}


CACHE = load(CACHE_PATH)
UNBANDED = load(UNBANDED_PATH)


def revalidate(theme, combo, hexes):
    out = []
    lo, hi = BANDS[theme]
    for hname, hx in zip(combo, hexes):
        Lv, C, H = lch(hx)
        dh = abs((H - OKABE_HUE[hname] + 180.0) % 360.0 - 180.0)
        if (C < C_FLOOR or dh > HUE_TOL or not meets_contrast(hx, theme)
                or not (lo - 1e-9 <= Lv <= hi + 1e-9)):
            return None
        out.append((hx, Lv, C, labs4(hx)))
    return out


W('# Lightness-banded palette re-run')
W('')
W('Generated by `band.py`. Every constraint from the main run still applies - '
  'hue fixed to an Okabe-Ito angle (+-' + fnum(HUE_TOL) + ' deg), '
  f'>= {fnum(MIN_CONTRAST)}:1 against BOTH the theme ground and the theme panel '
  'surface, objective = maximise the minimum CIEDE2000 over all pairs across '
  'normal vision and all three Brettel/Vienot/Mollon 1997 dichromacies - plus:')
W('')
W(f'* C* >= {fnum(C_FLOOR)}')
W(f'* light: every series L* in [{fnum(BANDS["light"][0])}, '
  f'{fnum(BANDS["light"][1])}]')
W(f'* dark: every series L* in [{fnum(BANDS["dark"][0])}, '
  f'{fnum(BANDS["dark"][1])}]')
W('')

# ---- how much of each band the contrast constraint actually allows ----------
W('## What the band and the contrast rule leave, before any search')
W('')
W('| theme | band asked for | L* actually reachable at C* >= 25 with 3:1 vs both |')
W('|---|---|---|')
reach = {}
pools = {}
for th in THEMES:
    pools[th] = {}
    allL = []
    for n in OKABE_ITO:
        p = candidates_for_hue(th, OKABE_HUE[n], *COARSE, c_min=C_FLOOR,
                               l_band=BANDS[th])
        pools[th][n] = p
        allL += [c[1] for c in p]
    reach[th] = (min(allL), max(allL)) if allL else None
    W(f'| {th} | [{fnum(BANDS[th][0])}, {fnum(BANDS[th][1])}] | '
      f'[{fnum(reach[th][0])}, {fnum(reach[th][1])}] |')
W('')
W('This is the first thing the numbers say, and it is not a search result. '
  'In the light theme the 3:1 floor against the `#FFFFFF` panel surface caps a '
  'C* >= 25 colour at about L* 60, so the top 12 L* of the requested [30, 72] '
  'band is empty - no colour can be placed there at all. In the dark theme the '
  '3:1 floor against the `#262624` surface sets the bottom of the reachable '
  'range at about L* 47, so the bottom 2 L* of [45, 88] is empty. The bands are '
  'therefore effectively [30, 60] and [47, 88]; I did not widen them.')
W('')
W('| hue | light candidates | dark candidates |')
W('|---|---|---|')
for n in OKABE_ITO:
    W(f'| {n} | {len(pools["light"][n])} | {len(pools["dark"][n])} |')
W('')

# ---- the search ------------------------------------------------------------
fine_cache = {th: {} for th in THEMES}


def fine_pool(th, name):
    if name not in fine_cache[th]:
        fine_cache[th][name] = candidates_for_hue(
            th, OKABE_HUE[name], *FINE, c_min=C_FLOOR, l_band=BANDS[th])
    return fine_cache[th][name]


results = {}
for th in THEMES:
    for k in (5, 6):
        val, combo, sel = best_palette(th, k, pools[th],
                                       lambda n, th=th: fine_pool(th, n), RESTARTS)
        ck = f'{th}|{k}'
        cached = CACHE.get(ck)
        if cached:
            csel = revalidate(th, cached['hues'], cached['hexes'])
            if csel is not None and score(csel) > val:
                val, combo, sel = score(csel), tuple(cached['hues']), csel
        CACHE[ck] = {'hues': list(combo), 'hexes': [c[0] for c in sel],
                     'min_de00': round(val, 4)}
        results[(th, k)] = (val, combo, sel)

json.dump(CACHE, open(CACHE_PATH, 'w'), indent=1, sort_keys=True)

W('## Banded palettes')
W('')
for th in THEMES:
    for k in (5, 6):
        val, combo, sel = results[(th, k)]
        items = [(f's{i+1}', c[0], c[3]) for i, c in enumerate(sel)]
        rep = set_report(items)
        d, a, b, v = rep['__worst__']
        t = THEMES[th]
        W(f'### {th}, {k} series, banded - min dE00 = {fnum(val, 2)}')
        W('')
        W('| series | hue | hex | L* | C* | vs ground | vs surface |')
        W('|---|---|---|---|---|---|---|')
        for i, (c, hname) in enumerate(zip(sel, combo)):
            W(f'| s{i+1} | {hname} | `{c[0]}` | {fnum(c[1])} | {fnum(c[2])} | '
              f'{fnum(contrast_ratio(c[0], t["ground"]), 2)}:1 | '
              f'{fnum(contrast_ratio(c[0], t["surface"]), 2)}:1 |')
        W('')
        W('| vision | min dE00 | worst pair |')
        W('|---|---|---|')
        for vv in VISIONS:
            dd, aa, bb = rep[vv]
            W(f'| {vv} | {fnum(dd, 2)} | {aa} ({combo[int(aa[1:])-1]}) / '
              f'{bb} ({combo[int(bb[1:])-1]}) |')
        W('')
        W(f'**Worst pair: {a} ({combo[int(a[1:])-1]}) / {b} '
          f'({combo[int(b[1:])-1]}) at dE00 = {fnum(d, 2)} under {v}.**')
        W('')

# ---- cost of the band ------------------------------------------------------
W('## What the band costs')
W('')
W('| theme | k | unbanded C*>=25 | banded | cost in dE00 | cost % |')
W('|---|---|---|---|---|---|')
for th in THEMES:
    for k in (5, 6):
        un = UNBANDED.get(f'{th}|{C_FLOOR}|{k}')
        b = results[(th, k)][0]
        if un:
            u = un['min_de00']
            W(f'| {th} | {k} | {fnum(u, 2)} | {fnum(b, 2)} | '
              f'{fnum(u - b, 2)} | {fnum(100.0 * (u - b) / u, 1)}% |')
        else:
            W(f'| {th} | {k} | (not in best_known.json) | {fnum(b, 2)} | - | - |')
W('')

# ---- neutral within the band ----------------------------------------------
W('## Best neutral inside the band')
W('')
W(f'Neutral = C* < {fnum(MAX_CHROMA_NEUTRAL)}, same 3:1 contrast rule, and now '
  'also inside the theme band.')
W('')
for th in THEMES:
    neus = neutral_candidates(th, 0.5, l_band=BANDS[th])
    for k in (5, 6):
        series = [(f's{i+1}', c[0], c[3]) for i, c in enumerate(results[(th, k)][2])]
        best = None
        for c in neus:
            v = min(pair_min(c[3], s[2]) for s in series)
            if best is None or v > best[0]:
                best = (v, c)
        val, c = best
        worst = None
        for s in series:
            for vi, vv in enumerate(VISIONS):
                dd = ciede2000(c[3][vi], s[2][vi])
                if worst is None or dd < worst[0]:
                    worst = (dd, s[0], vv)
        combo = results[(th, k)][1]
        W(f'* **{th}, against the banded {k}-series set**: `{c[0]}` '
          f'(L* {fnum(c[1])}, C* {fnum(c[2])}), min dE00 = **{fnum(val, 2)}**, '
          f'closest to {worst[1]} ({combo[int(worst[1][1:])-1]}) under {worst[2]}.')
    W('')

# ---- hatch: opaque ground, one rule for both themes ------------------------
W('## Hatch stripe: theme ground at alpha 1.00')
W('')
W('One rule, both themes: the stripe is the theme ground colour, fully opaque, '
  'over the banded 5-series palette. Contrast is stripe against its own series '
  'fill.')
W('')
hatch = {}
for th in THEMES:
    g = THEMES[th]['ground']
    val, combo, sel = results[(th, 5)]
    W(f'### {th} (stripe `{g}`)')
    W('')
    W('| series | hue | fill | stripe | contrast | >= 3:1 |')
    W('|---|---|---|---|---|---|')
    rows = []
    for i, (c, hname) in enumerate(zip(sel, combo)):
        cr = contrast_ratio(g, c[0])
        # alpha 1.00 composite of an opaque colour is that colour; assert it
        assert composite_over(g, 1.0, c[0]) == g.upper()
        rows.append((f's{i+1}', hname, c[0], cr))
        W(f'| s{i+1} | {hname} | `{c[0]}` | `{g}` | {fnum(cr, 2)}:1 | '
          f'{"PASS" if cr >= MIN_CONTRAST else "**FAIL**"} |')
    worst = min(rows, key=lambda r: r[3])
    hatch[th] = worst
    W('')
    W(f'**Worst series: {worst[0]} ({worst[1]}) `{worst[2]}` at '
      f'{fnum(worst[3], 2)}:1 - '
      f'{"clears" if worst[3] >= MIN_CONTRAST else "does NOT clear"} 3:1.**')
    W('')

W(f'One rule holds for both themes: '
  + ('yes, every series in both themes clears 3:1.'
     if min(h[3] for h in hatch.values()) >= MIN_CONTRAST
     else 'no - see the failing series above.'))
W('')
W(f'Run time: {fnum(time.time() - t0, 1)} s.')
W('')

open('BAND_RESULTS.md', 'w').write('\n'.join(L))
print('wrote BAND_RESULTS.md (%.1f s)' % (time.time() - t0))
